### ISSUE TITLE
Violation codes shadow flake8-import-order

### ISSUE THREAD

**Issue by labrys** [adamchainz/flake8-tidy-imports#106]
`I201: Banned import 'foo' used` is also used by `flake8-import-order` as `I201: Missing newline between import groups.`

**Comment by adamchainz** [comment]
Ok, so you think this library should change?

**Comment by labrys** [comment]
Personally I think the flake8 error code system should change, but that's neither here nor there 😁
Of course it's up to you to decide, but right now the two aren't compatible.  I would recommend changing `flake8-tidy-imports` to higher `I2xx` codes.

**Comment by adamchainz** [comment]
Could you open a PR adding +50 to them all? thx

**Comment by labrys** [comment]
Sure will do :)
