### ISSUE TITLE
Ban relative imports?

### ISSUE THREAD

**Issue by proofit404** [adamchainz/flake8-tidy-imports#153]
Hi, thank you for the useful package!

I wonder if it would be desirable to introduce the third rule to the plugin?

What do you think about the possibility of forbidding relative imports?

For example,
```python
# bad
from .foo import Bar
# good
from quiz.foo import Bar
```
Have a good day :tada: 

Best regards,
Artem.

**Comment by adamchainz** [comment]
Hey Artem,

I think this is a good idea. I think it should be another configuration option `ban-relative-imports = true` or similar.

If you'd like to look into a PR that would be fantastic.

Adam

**Comment by proofit404** [comment]
Good morning!

I would try to implement it. Not sure if it'll go smooth.

**Comment by proofit404** [comment]
Please, take a look at https://github.com/adamchainz/flake8-tidy-imports/pull/154

Best regards,
Artem.

**Comment by adamchainz** [comment]
Added in #154

**Comment by adamchainz** [comment]
Released in version 3.0.0! https://pypi.org/project/flake8-tidy-imports/

**Comment by proofit404** [comment]
Thanks! :tada: :cake: :tada:
