### ISSUE TITLE
I251 can't be configured to restrict importing of modules within packages

### ISSUE THREAD

**Issue by prophile** [adamchainz/flake8-tidy-imports#177]
For example, there's no way to ban an entire library; adding a ban on `badlibrary` via `banned-modules` prevents `import badlibrary` but not `import badlibrary.othermodule`, and wildcards are not matched.

**Comment by adamchainz** [comment]
Oh, it really should ban `badlibrary.othermodule`. Definitely an oversight. Would you like to make a PR?

**Comment by chriselion** [comment]
Would you still accept a PR for this? If so, I might be able to make one.

**Comment by adamchainz** [comment]
Yes. Perhaps we could use the syntax "foo.*"

**Comment by chriselion** [comment]
Sounds good (and backwards compatible).

Do you think it should do an actual regex match? Or some other wildcard function (maybe fnmatch.fnmatchcase)?
