### ISSUE TITLE
Ban absolute imports

### ISSUE THREAD

**Issue by cthoyt** [adamchainz/flake8-tidy-imports#198]
First, awesome tool. I am adding it to my list of flask plugins :)

However, I guess we have different opinions. I would like an option to explicitly ban absolute imports.

I find that people accidentally create circular dependencies that are difficult to resolve much more often when there are absolute imports. Also, it gives people the idea that they can run python files as scripts, which i want to stop my co-developers from doing in favor of them using `python -m ...`

However, I wouldn't want to ban absolute imports in my `tests/` directory, which should be able to run without knowing anything about how my package is written or structured in the `src/` directory.

**Comment by adamchainz** [comment]
>However, I guess we have different opinions. I would like an option to explicitly ban absolute imports.

Yup completely different opinions.

> I find that people accidentally create circular dependencies that are difficult to resolve much more often when there are absolute imports.

Can you give an example? Relative imports do nothing to help circular dependencies afaiu.

> However, I wouldn't want to ban absolute imports in my tests/ directory, which should be able to run without knowing anything about how my package is written or structured in the src/ directory.

I don't think we could support that setup as a plugin. You could support that without running flake8 twice once on src and once on tests, with separate configs.

Anyway you can do this already by just banning imports of the modules within your app:

```ini
[flake8]
banned-modules =
    myproject = use relative imports!
```

I guess we could add a docs change to show this?

**Comment by cthoyt** [comment]
Now that I think of it, this behavior might not exist anymore, but I think pycharm can catch circular imports with relative imports but doesn't even bother to look/can't figure out absolute imports. Do you have any blog posts I could read that promote absolute over relative imports? I'm definitely of the opinion that importing names is crazy - I always dot prefix things.

Hmm I guess that solution would work.

Maybe to address the other issue would be to have the ability to specify blacklisted files or folders? But that would mean messing with flake8 instead of your package. I guess a solution for me would be to make a different tox environment to run with this. I think we could consider this issue closed but I'm interested if you have other thoughts

**Comment by adamchainz** [comment]
> Do you have any blog posts I could read that promote absolute over relative imports?

It's right there in PEP8: https://www.python.org/dev/peps/pep-0008/

> Absolute imports are recommended

TBH if pycodestyle rigorously implemented PEP8, rather than 90% of it, there'd be no need for this plugin.

> I'm definitely of the opinion that importing names is crazy - I always dot prefix things.

I think a balance is required. Importing names is very useful if you're going to use them repeatedly. The only downside I know about importing names is that it can make mocking harder. I don't think that's a good reason as we should be avoiding mocking as much as possible.

> I guess a solution for me would be to make a different tox environment to run with this.

Yes, if you use pre-commit you could have two hooks filtered by filename matches.
