### ISSUE TITLE
Ban relative imports, not working

### ISSUE THREAD

**Issue by louwers** [adamchainz/flake8-tidy-imports#203]
I put
```
from . import test
```
in one of my source files that is being checked.

However `flake8 --ban-relative-imports` does not pick up on it.

I cannot create a minimal example, because minimal examples work.

When I create another problem in the same file flake8 does pick up on it. Please assist me in finding the problem.

**Comment by adamchainz** [comment]
Works for me:


```
$ cat ~/tmp/test.py
from . import test
$ .tox/py38/bin/flake8 --ban-relative-imports ~/tmp/test.py
/Users/chainz/tmp/test.py:1:1: F401 '.test' imported but unused
/Users/chainz/tmp/test.py:1:1: I252 Relative imports are banned.
```

I also added a test to cover CLI usage in #204.

Does the plugin show up in your `flake8 --version` ? Did you try using the config file? Did you use the latest version of everything?

**Comment by louwers** [comment]
```
(venv) [bart.local@localhost librarian]$ flake8 --version
3.8.1 (flake8-tidy-imports: 4.1.0, mccabe: 0.6.1, pycodestyle: 2.6.0,
pyflakes: 2.2.0) CPython 3.6.10 on Linux
```
After some more testing it seems that when I disable my configuration file altogether and use the flag it works.

**Comment by louwers** [comment]
`select` was in my `.flake8` file. Thanks!
