### ISSUE TITLE
I252 does not allow for fine-tuning

### ISSUE THREAD

**Issue by AzariasB** [adamchainz/flake8-tidy-imports#299]
### Python Version

3.9.0

### Package Version

latest

### Description

It's more of a feature request than an issue :

Currently I252 can only be a boolean
```
ban-relative-imports = True
```

As stated by the [pep documentation](https://www.python.org/dev/peps/pep-0008/#imports) using relative import, is acceptable when dealing with complex package layouts.
```python3
from .sibling import example
# is more readable than
from my.project.sub.module.sibling import example
```

But abusing the relative import by searching into a parent module makes it less readable
```python3
from ....parent import example
# is less readable than
from my.project.parent import example
```

So the idea would be to have an option to specify the maximum level of *relativeness* that is allowed in the project
Something like
```
max-relative-import = 1
```
```python3
# This would pass
from .sibling import example

# This would fail
from ..parent import example 
```
(I'm not good at naming things so any idea is welcome !)

I can make a PR if needed :)

**Comment by adamchainz** [comment]
I think this would be reasonable. But I can't why one would want to allow levels > 1, i.e. `from ..` but not `from ...`.

Perhaps we could avoid changing things too much by reusing the existing configuration option with a special value like `ban-relative-imports = non-peers`.

Would you like to look into a PR?

**Comment by AzariasB** [comment]
Indeed, level > 1 imports are never a good practice.

> Perhaps we could avoid changing things too much by reusing the existing configuration option with a special value like `ban-relative-imports = non-peers`.
I really like the option to keep the existing configuration and adding a new special value !

Yep, I'll look into a PR !
