### ISSUE TITLE
Feature request: special `banned-modules` entry for os.path and friends

### ISSUE THREAD

**Issue by flying-sheep** [adamchainz/flake8-tidy-imports#308]
There’s many APIs replaced by `pathlib`, and not all of them are in `os.path`: https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module

It would be great to be able to ban them all with a special `banned-modules` entry like the `{python2to3}` one.

**Comment by flying-sheep** [comment]
Hmm, seems like `banned-modules` doesn’t find use of things like `os.remove` at all!

**Comment by adamchainz** [comment]
It works on the import statement only. So you can ban `import os` but that is not a good idea.

**Comment by adamchainz** [comment]
This sounds like a job for a different plugin, perhaps with individual rules to suggest the pathlib code to replace the `os` code with.

**Comment by flying-sheep** [comment]
OK!
