### ISSUE TITLE
Errors are bizrre for non-module import

### ISSUE THREAD

**Issue by lucaswiman** [adamchainz/flake8-tidy-imports#38]
Many frameworks and libraries deprecate/remove individual classes or methods _within_ a module. For example, `django.core.management.NoArgsCommand` was removed in Django 1.10, but the `django.core.management` module still exists.  

While `flake8-tidy-imports` works correctly for these cases, the error message is somewhat confusing:
```
I201 Banned module 'django.core.management.NoArgsCommand' imported - Use django.core.management.BaseCommand instead
```

But `NoArgsCommand` isn't a module, it's a class! I propose changing the message from "Banned module" to "Banned Import" so the error message is not incorrect in both the module and the method/class cases.

This is a fairly pedantic issue, so feel free to close as "wontfix" if you don't want to be bothered. If you're amenable to the change, I'd be happy to implement it. :-)

BTW, thanks for writing this library! It seems to be quite useful for helping with framework upgrades and migrating to Python 3.

**Comment by adamchainz** [comment]
Sure, change it!
