### ISSUE TITLE
Ban relative imports only when through the root of the package

### ISSUE THREAD

**Issue by PeterJCLaw** [adamchainz/flake8-tidy-imports#394]
### Description

I have a (Django) project where we ban relative imports which go through the root of the project, however mostly allow them otherwise.
Would you be open to a PR which extends the `ban-relative-imports` behaviour with a `root` value to ban these?

For example given a project like:
```
$ tree mypkg/
mypkg/
├── left
│   ├── child
│   │   ├── __init__.py
│   │   └── utils.py
│   ├── __init__.py
│   ├── main.py
│   └── sibling_left.py
└── right
    ├── __init__.py
    ├── main.py
    └── sibling_right.py
```

Then for imports in `mypkg/left/main.py`:
``` python
from .sibling_left import A  # ok
from .child.utils import B  # ok
from ..right import X  # not ok
from ..right.main import Y  # not ok
```

Or for imports in `mypkg/left/child/utils.py`:
``` python
from ..sibling_left import A  # ok
from ...right import X  # not ok
from ...right.main import Y  # not ok
```

Currently we have a project-local linter implementation which does this, though it relies on a hard-coded path to know the project root. I can see that knowing the project root automatically might be a stumbling block for generalising this, so suggestions towards that would be welcome!

**Comment by adamchainz** [comment]
The rule docs quote PEP8’s guidance on preferring absolute imports, which is what I want to lint for here.

I don't think this import scheme fits in with that. I personally struggle with the mental arithmetic when there’s >1 dot. Thus, I don't want to support alternative schemes here. You could try with a local flake8 plugin in your project.
