### ISSUE TITLE
Require minimal local imports for siblings

### ISSUE THREAD

**Issue by PeterJCLaw** [adamchainz/flake8-tidy-imports#395]
### Description

I'd like to be able to require that immediate sibling imports are always relative (and in their minimal form).

For example, given a project structure like:
```
$ tree mypkg/
mypkg/
├── child
│   ├── __init__.py
│   └── utils.py
├── __init__.py
├── main.py
└── sibling.py
```

Then in `main.py`:
``` python
from mypkg import sibling  # bad
from mypkg.sibling import A  # bad

from . import sibling  # good
from .sibling import A  # good
```

Not sure what the rule should be for `child` as the project I want to use this in is a Django project where we don't tend to expose things via `__init__.py`. Probably we'd treat `child/__init__.py` as if it were a `child.py` given that the imports look the same.

This miight have the same requirement around knowing the project root that https://github.com/adamchainz/flake8-tidy-imports/issues/394 does, though there are plenty of other relative spellings which could be prohibited without that.

**Comment by adamchainz** [comment]
PEP8 says “absolute imports are preferred”, which is what the relative import rule in flake8-tidy-imports helps enforce, in one form or another. Your ask here is for a rule to prefer relative imports, and thus I don't want to implement/support that as it's against PEP8.

I'd again suggest trying a local plugin.
