### ISSUE TITLE
Add a `grandparents` option to `ban-relative-imports`

### ISSUE THREAD

**Issue by GideonBear** [adamchainz/flake8-tidy-imports#414]
### Description

This would ban relative imports with more than two dots (eg `from ...a.b import c`), just like `parents` does, but for grandparents.
I personally like relative imports, but with three dots it becomes unreadable.

If this is accepted, I would be interested in submitting a PR for this.

**Comment by adamchainz** [comment]
The `parents` follows PEP8, which allows sibling imports but no more. I don't want to go down the road of adding an option for every personal preference. You can copy from flake8-tidy-imports into your own project-level plugin if you really want this.

**Comment by GideonBear** [comment]
That's understandable, thanks for the reply. I'll make a fork if I have the time.
