### ISSUE TITLE
Allow `*` to match part of a module or package name

### ISSUE THREAD

**Issue by ericbn** [adamchainz/flake8-tidy-imports#418]
### Description

Hi 👋

I'd like to ban all packages listed in https://youtype.github.io/boto3_stubs_docs/#packages. That's 337 packages as of the time I created this feature request...

It would be great if I could just define:
```
banned-modules =
    mypy_boto3_*.* = This is a dev dependency only
```
So `mypy_boto3_*` would match any package name starting with `mypy_boto3_`.

Other ideas: Maybe `*` could be even used in any part of the name, e.g. `foo*bar`, `*baz`. Or multiple `*` could be allowed too, e.g. `*f*o*`. Also, since only `*` is used as wildcard, other [glob characters](https://docs.python.org/3/library/fnmatch.html) like `?` or `[]` would not be considered as wildcard.

I'll be happy to submit a PR if you agree.

**Comment by adamchainz** [comment]
This seems kind of niche. Why do you want to ban their imports? And I cannot think of another situation where you'd want to glob packages to ban.

I think I lean towards “that’s out of scope” here. You can always create a custom lint rule in fairly little code.

**Comment by ericbn** [comment]
As for why I want to explicitly ban them: There are two usage modes for these packages. One with boto3-stubs, where all typing is automated and [implicit](https://youtype.github.io/boto3_stubs_docs/mypy_boto3_sqs/usage/#implicit-type-annotations), and another with boto3-stubs-lite, where typing must be [explicit](https://youtype.github.io/boto3_stubs_docs/mypy_boto3_sqs/usage/#explicit-type-annotations). We're using the implicit mode and only installing the `mypy_boto3_*` packages for linting. Packages won't be available during runtime, so we want to prevent any developer of our team from mistakenly taking the "explicit" approach, as imports will fail.

Yeah, I cannot think of any other set of packages that one would want to ban with a glob other than this one... Too bad they didn't name their packages `mypy_boto3.*` instead.

**Comment by adamchainz** [comment]
I think for now I'll close it. If a second use case comes up, we can re-consider.
