### ISSUE TITLE
Ban import for file pattern

### ISSUE THREAD

**Issue by Niccolum** [adamchainz/flake8-tidy-imports#424]
### Description

Thanks for your library!

For me and my command it will be nice to have possibility to import some local files in a certain way.

For example, I have 
```
controllers/
- __init__.py
- controller1.py
- controller2.py
```
In `__init__.py` i write
```
from .controller1 import ControllerOne
from .controller2 import ControllerTwo
```
And inside `controller1.py` i want to use `ControllerTwo`.

So, if i write in `controller1.py`
```
from controllers import ControllerTwo
```
it will be a circular import,  but if I write something like
```
from controllers.controller2 import ControllerTwo 
```
It will work.

So, I want to restrict in some files import some modules "in short way" to avoid circular import. But outside controllers - any files can import any controller in short way 

Is it possible with your plugin to do somethibg like it? Could you consider such functionality for yourself?

Thanks for any reply!

**Comment by adamchainz** [comment]
I like this idea for neatness - we do the same kind of thing within Django. But I think the request is too complicated for this plugin. For fine-grained import rules, you can use [Import Linter](https://import-linter.readthedocs.io/en/latest/readme.html).

**Comment by Niccolum** [comment]
Thanks for your response, @adamchainz . I saw this tool, but it's so hard to use it without https://github.com/seddonym/import-linter/issues/56
Oh, i will waiting. Thanks!
